Portafolio_Django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


from portafolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

#from .views import render_posts
from . import views

app_name = 'blog'


urlpatterns = [
    path('',views.render_posts, name='posts'),
    path("<int:post_id>", views.post_detail, name="post_detail"),
]

blog/models.py
from django.db import models
import datetime
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

portafolio/models.py
from django.db import models

from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date
# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portapolio/images")
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render, get_list_or_404
from .models import Post


# Create your views here.

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {"posts" : posts})


def post_detail(request, post_id):
    post = get_list_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {'post': post})

portafolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
<h1>post detail</h1>

<h2>{{post.title}}</h2>

<p>{{post.description}}</p>

<img src="{{post.image.url}}" alt="{{post.title}}">

blog/templates/posts.html
<h1>Aqui todos los Posts</h1>
{% for post in posts %}
    <h2>{{post.title}}</h2>
    <h3>{{post.date}}</h3>
    <p>{{post.description}}</p>
    <img src="{{post.image.url}}" alt="{{post.title}}">
    <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
{% endfor %}

portafolio/templates/home.html
<h1>hola</h1>
<pre>{{projects}}</pre>

{% for project in projects %}
<h2>{{project.title}}</h2>
<p>{{project.description}}</p>
<img src="{{project.image.url}}" alt="{{project.title}}">
{% if project.url %}
<a href="{{project.url}}">{{project.url}}</a>
{% endif %}

{% endfor %}